const traducoes = {
    pt: {
        // Globais (Header, Footer e CTAs padrões)
        "navInicio": "Início",
        "navLocalizacao": "Localização",
        "navImpacto": "Impacto",
        "navProdutos": "Produtos",
        "navSobreNos": "Sobre nós",
        "footSub": "Tecnologia que impulsiona a biotecnologia",
        "footProd": "Produtos",
        "footMais": "Mais Smart",
        "footCont": "Contatos",
        "btnEquipe": "Faça parte da nossa equipe",
        "btnHistoria": "Nossa história",
        "btnChegar": "Como chegar",

        // Específicos da página Impacto
        "impHeroBread": "Início > Impacto",
        "impHeroTitle": "Descubra os benefícios e a eficiência dos nossos produtos para o mundo",
        "impSecLabel1": "IMPACTO",
        "impResiduoTit": "Do Resíduo à Transformação Sustentável",
        "impResiduoDesc": "A Smart Bugs conecta inovação, economia circular e produção de proteína sustentável através da criação industrial de insetos.",
        "impStatCO2": "menos emissão de CO2",
        "impStatAgua": "menos consumo de água",
        "impStatArea": "menos área ocupada",
        "impStat360": "Economia circular360°",
        "impSecLabel2": "CICLO 360°",
        "impEtapasTit": "Observe o impacto  em cada etapa",
        "impEtapasDesc": "A economia circular transforma resíduos em recursos valiosos para uma produção sustentável",
        "impEtapa1Tit": "Resíduo",
        "impEtapa1Desc": "Coleta e triagem de resíduos orgânicos",
        "impEtapa2Tit": "Larva",
        "impEtapa2Desc": "Bioconversão dos resíduos em larvas ricas em nutrientes.",
        "impEtapa3Tit": "Proteína",
        "impEtapa3Desc": "Larvas processadas que se tornam proteína de alto valor biológico.",
        "impEtapa4Tit": "Fertilizante",
        "impEtapa4Desc": "Substrato transformado em fertilizante natural e nutritivo.",
        "impEtapa5Tit": "Solo",
        "impEtapa5Desc": "O fertilizante devolve nutrientes ao solo e inicia um novo ciclo.",
        "impBannerTit": "Menos resíduos. Mais Vida",
        "impBannerDesc": "Nosso processo gera um impacto positivo real no planeta, comparado aos métodos tradicionais de produção de proteína.",
        "impBannerCO2": "menos emissãode CO2",
        "impBannerAgua": "menos consumode água",
        "impBannerArea": "Menos áreaocupada",
        "impCtaLabel": "INTERESSADO?",
        "impCtaTit": "Nos acompanhe nessa jornada, para fazer do mundo, um lugar melhor"
    },
    en: {
        // Globais
        "navInicio": "Home",
        "navLocalizacao": "Location",
        "navImpacto": "Impact",
        "navProdutos": "Products",
        "navSobreNos": "About us",
        "footSub": "Technology driving biotechnology",
        "footProd": "Products",
        "footMais": "More Smart",
        "footCont": "Contacts",
        "btnEquipe": "Join our team",
        "btnHistoria": "Our story",
        "btnChegar": "How to get here",

        // Específicos da página Impacto
        "impHeroBread": "Home > Impact",
        "impHeroTitle": "Discover the benefits and efficiency of our products for the world",
        "impSecLabel1": "IMPACT",
        "impResiduoTit": "From Waste to Sustainable Transformation",
        "impResiduoDesc": "Smart Bugs connects innovation, circular economy, and sustainable protein production through industrial insect farming.",
        "impStatCO2": "less CO2 emissions",
        "impStatAgua": "less water consumption",
        "impStatArea": "less land use",
        "impStat360": "360° Circular Economy",
        "impSecLabel2": "360° CYCLE",
        "impEtapasTit": "Observe the impact  at each stage",
        "impEtapasDesc": "The circular economy turns waste into valuable resources for sustainable production.",
        "impEtapa1Tit": "Waste",
        "impEtapa1Desc": "Collection and sorting of organic waste.",
        "impEtapa2Tit": "Larva",
        "impEtapa2Desc": "Bioconversion of waste into nutrient-rich larvae.",
        "impEtapa3Tit": "Protein",
        "impEtapa3Desc": "Processed larvae become high biological value protein.",
        "impEtapa4Tit": "Fertilizer",
        "impEtapa4Desc": "Substrate transformed into natural, nutritious fertilizer.",
        "impEtapa5Tit": "Soil",
        "impEtapa5Desc": "Fertilizer returns nutrients to the soil to begin a new cycle.",
        "impBannerTit": "Less Waste. More Life.",
        "impBannerDesc": "Our process creates a real positive impact on the planet compared to traditional protein production methods.",
        "impBannerCO2": "less CO2 emissions",
        "impBannerAgua": "less water consumption",
        "impBannerArea": "less land use",
        "impCtaLabel": "INTERESTED?",
        "impCtaTit": "Join us on this journey to make the world a better place."
    },
    es: {
        // Globais
        "navInicio": "Inicio",
        "navLocalizacao": "Ubicación",
        "navImpacto": "Impacto",
        "navProdutos": "Productos",
        "navSobreNos": "Sobre nosotros",
        "footSub": "Tecnología que impulsa la biotecnología",
        "footProd": "Productos",
        "footMais": "Más Smart",
        "footCont": "Contactos",
        "btnEquipe": "Forma parte de nuestro equipo",
        "btnHistoria": "Nuestra historia",
        "btnChegar": "Cómo llegar",

        // Específicos da página Impacto
        "impHeroBread": "Inicio > Impacto",
        "impHeroTitle": "Descubre los beneficios y la eficiencia de nuestros productos para el mundo",
        "impSecLabel1": "IMPACTO",
        "impResiduoTit": "Del Residuo a la Transformación Sostenible",
        "impResiduoDesc": "Smart Bugs conecta innovación, economía circular y producción de proteína sostenible a través de la cría industrial de insectos.",
        "impStatCO2": "menos emisión de CO2",
        "impStatAgua": "menos consumo de agua",
        "impStatArea": "menos área ocupada",
        "impStat360": "Economía circular 360°",
        "impSecLabel2": "CICLO 360°",
        "impEtapasTit": "Observa el impacto en cada etapa",
        "impEtapasDesc": "La economía circular transforma residuos en recursos valiosos para una producción sostenible.",
        "impEtapa1Tit": "Residuo",
        "impEtapa1Desc": "Recolección y clasificación de residuos orgánicos.",
        "impEtapa2Tit": "Larva",
        "impEtapa2Desc": "Bioconversión de residuos en larvas ricas en nutrientes.",
        "impEtapa3Tit": "Proteína",
        "impEtapa3Desc": "Larvas procesadas que se convierten en proteína de alto valor biológico.",
        "impEtapa4Tit": "Fertilizante",
        "impEtapa4Desc": "Sustrato transformado en fertilizante natural y nutritivo.",
        "impEtapa5Tit": "Suelo",
        "impEtapa5Desc": "El fertilizante devuelve nutrientes al suelo para iniciar un nuevo ciclo.",
        "impBannerTit": "Menos residuos. Más Vida.",
        "impBannerDesc": "Nuestro proceso genera un impacto positivo real en el planeta, en comparación con los métodos tradicionales de producción de proteína.",
        "impBannerCO2": "menos emisión de CO2",
        "impBannerAgua": "menos consumo de agua",
        "impBannerArea": "Menos área ocupada",
        "impCtaLabel": "¿INTERESADO?",
        "impCtaTit": "Acompáñanos en esta jornada para hacer del mundo un lugar mejor."
    }
};