const traducoes = {
    pt: {
        navInicio: "Início",
        navLocalizacao: "Localização",
        navImpacto: "Impacto",
        navProdutos: "Produtos",
        navSobreNos: "Sobre nós",
        heroTitulo: "Inovação e tecnologia para o sucesso das suas criações",
        heroDesc: "Trabalhamos juntos para buscar a inovação das suas criações através de soluções tecnológicas inteligentes, transformando desafios complexos de reprodução em processos simples, sustentáveis e altamente produtivos.",
        benTitulo: "Benefícios",
        benSub: "Soluções práticas desenhadas para elevar a eficiência e o rendimento do seu cultivo.",
        ben1Tit: "Sustentabilidade de Alta Performance",
        ben1Desc: "Otimize o cultivo de insetos com processos focados na economia circular, reduzindo o desperício de recursos biológicos. Implemente tecnologia de ponta que não apenas produz, mas contribui ativamente para um ecossistema produtivo mais limpo e equilibrado.",
        ben2Tit: "Escalabilidade para Bio-fábricas",
        ben2Desc: "Nossas ferramentas possuem design modular para crescer conforme sua demanda aumenta. Com interfaces intuitivas, facilitamos o manejo das larvas e aceleramos o retorno sobre o investimento da sua unidade de produção.",
        ben3Tit: "Aceleração do Ciclo Produtivo",
        ben3Desc: "Nossas ferramentas são projetadas para otimizar o tempo de manejo e acelerar o desenvolvimento das larvas em cada fase. Através de um design funcional, eliminamos gargalos operacionais e permitimos que sua produção atinja o ponto de colheita com muito mais rapidez e eficiência.",
        impTit: "Tecnologia que gera transformação real",
        impSub: "Nossas soluções para a criação de insetos otimizam o uso de recursos físicos, acelerando o ciclo de vida das larvas com maior eficiência produtiva do que os métodos convencionais.",
        imp1: "Eficiência de Manejo: Reduzimos significativamente o tempo operacional em cada fase do ciclo produtivo.",
        imp2: "Otimização de Recursos: Minimizamos o desperdício de insumos orgânicos e maximizamos a produtividade.",
        imp3: "Escalabilidade e Futuro: Ajudamos produtores a expandir suas bio-fábricas com equipamentos modulares que atendem à demanda.",
        btnImpacto: "Veja nosso impacto",
        praTit: "Do Impacto à Prática",
        praSub: "Nossos produtos são focados na eficiência de reprodução de insetos, como larvas.",
        btnCatalogo: "Catálogo de Produtos",
        card1Tit: "Caixa Reprodutor",
        card1Desc: "Primeira caixa autoempilhável da América Latina.",
        btnSaibaMais: "Saiba Mais",
        emBreve: "Em Breve...",
        intTit: "Se interessou?",
        intSub: "Somos desenvolvedores e entusiastas da sustentabilidade focados em otimizar cada fase do ciclo das larvas.",
        btnHistoria: "Nossa história",
        btnChegar: "Como chegar",
        intP1: "A Smart Bugs nasceu da vontade de transformar o cenário da biotecnologia através de soluções inteligentes e acessíveis. Combinamos tecnologia e biologia para entregar ferramentas que realmente fazem a diferença na produção de proteínas sustentáveis.",
        intP2: "Nosso compromisso é com a inovação, a sustentabilidade e o sucesso dos nossos clientes. Estamos aqui para ajudar você a alcançar resultados extraordinários, otimizando cada etapa do ciclo produtivo de larvas com eficiência e responsabilidade ambiental.",
        intP3: "Junte-se a nós nessa jornada de transformação e descubra como a Smart Bugs pode impulsionar o futuro da biotecnologia, tornando o processo de criação de insetos mais inteligente, eficiente e sustentável.",
        footSub: "Tecnologia que impulsiona a biotecnologia",
        footProd: "Produtos",
        footMais: "Mais Smart",
        footCont: "Contatos",
        btnEquipe: "Faça parte da nossa equipe"
    },
    en: {
        // Globais
        "navInicio": "Home",
        "navLocalizacao": "Location",
        "navImpacto": "Impact",
        "navProdutos": "Products",
        "navSobreNos": "About us",
        "footSub": "Technology driving biotechnology",
        "footProd": "Products",
        "footMais": "More Smart",
        "footCont": "Contacts",
        "btnEquipe": "Join our team",
        "footLinkHist": "Discover our story",
        "footLinkPlan": "Where we plan to go",
        "emBreve": "Coming Soon...",
        heroTitulo: "Innovation and technology for the success of your breeding",
        heroDesc: "We work together to seek innovation for your breeding through intelligent technological solutions, transforming complex reproduction challenges into simple, sustainable, and highly productive processes.",
        benTitulo: "Benefits",
        benSub: "Practical solutions designed to increase the efficiency and yield of your farming.",
        ben1Tit: "High-Performance Sustainability",
        ben1Desc: "Optimize insect farming with processes focused on the circular economy, reducing the waste of biological resources. Implement cutting-edge technology that not only produces but actively contributes to a cleaner and more balanced productive ecosystem.",
        ben2Tit: "Scalability for Bio-factories",
        ben2Desc: "Our tools feature a modular design to grow as your demand increases. With intuitive interfaces, we facilitate larvae management and accelerate the return on investment of your production unit.",
        ben3Tit: "Production Cycle Acceleration",
        ben3Desc: "Our tools are designed to optimize handling time and accelerate larvae development at each phase. Through functional design, we eliminate operational bottlenecks and allow your production to reach the harvest point much faster and more efficiently.",
        impTit: "Technology that generates real transformation",
        impSub: "Our insect farming solutions optimize the use of physical resources, accelerating the larvae life cycle with greater productive efficiency than conventional methods.",
        imp1: "Handling Efficiency: We significantly reduce operational time in each phase of the production cycle.",
        imp2: "Resource Optimization: We minimize the waste of organic inputs and maximize productivity.",
        imp3: "Scalability and Future: We help producers expand their bio-factories with modular equipment that meets demand.",
        btnImpacto: "See our impact",
        praTit: "From Impact to Practice",
        praSub: "Our products are focused on the reproductive efficiency of insects, such as larvae.",
        btnCatalogo: "Product Catalog",
        card1Tit: "Breeding Box",
        card1Desc: "The first self-stacking box in Latin America.",
        btnSaibaMais: "Learn More",
        emBreve: "Coming Soon...",
        intTit: "Interested?",
        intSub: "We are developers and sustainability enthusiasts focused on optimizing every phase of the larvae cycle.",
        btnHistoria: "Our history",
        btnChegar: "How to get there",
        intP1: "Smart Bugs was born from the desire to transform the biotechnology landscape through smart and accessible solutions. We combine technology and biology to deliver tools that truly make a difference in sustainable protein production.",
        intP2: "Our commitment is to innovation, sustainability, and the success of our clients. We are here to help you achieve extraordinary results, optimizing every stage of the larvae production cycle with efficiency and environmental responsibility.",
        intP3: "Join us on this journey of transformation and discover how Smart Bugs can boost the future of biotechnology, making the insect farming process smarter, more efficient, and sustainable.",
        footSub: "Technology that drives biotechnology",
        footProd: "Products",
        footMais: "More Smart",
        footCont: "Contacts",
        btnEquipe: "Join our team",
        footCaixa: "Reproduction Box",
        footDescubra: "Discover our history",
        footPlanejamos: "Where do we plan to go"
    },
    es: {
        "navInicio": "Inicio",
        "navLocalizacao": "Ubicación",
        "navImpacto": "Impacto",
        "navProdutos": "Productos",
        "navSobreNos": "Sobre nosotros",
        "footSub": "Tecnología que impulsa la biotecnología",
        "footProd": "Productos",
        "footMais": "Más Smart",
        "footCont": "Contactos",
        "btnEquipe": "Forma parte de nuestro equipo",
        "footLinkHist": "Descubre nuestra historia",
        "footLinkPlan": "A dónde planeamos llegar",
        "emBreve": "Próximamente...",
        
        heroTitulo: "Innovación y tecnología para el éxito de sus crías",
        heroDesc: "Trabajamos juntos para buscar la innovación de sus crías a través de soluciones tecnológicas inteligentes, transformando desafíos complejos de reproducción en procesos simples, sostenibles y altamente productivos.",
        benTitulo: "Beneficios",
        benSub: "Soluciones prácticas diseñadas para elevar la eficiencia y el rendimiento de su cultivo.",
        ben1Tit: "Sostenibilidad de Alto Rendimiento",
        ben1Desc: "Optimice el cultivo de insectos con procesos enfocados en la economía circular, reduciendo el desperdicio de recursos biológicos. Implemente tecnología de punta que no solo produce, sino que contribuye activamente a un ecosistema productivo más limpio y equilibrado.",
        ben2Tit: "Escalabilidad para Bio-fábricas",
        ben2Desc: "Nuestras herramientas tienen un diseño modular para crecer a medida que aumenta su demanda. Con interfaces intuitivas, facilitamos el manejo de las larvas y aceleramos el retorno de la inversión de su unidad de producción.",
        ben3Tit: "Aceleración del Ciclo Productivo",
        ben3Desc: "Nuestras herramientas están diseñadas para optimizar el tiempo de manejo y acelerar el desarrollo de las larvas en cada fase. A través de un diseño funcional, eliminamos cuellos de botella operativos y permitimos que su producción alcance el punto de cosecha mucho más rápido y de manera más eficiente.",
        impTit: "Tecnología que genera una transformación real",
        impSub: "Nuestras soluciones para la cría de insectos optimizan el uso de recursos físicos, acelerando el ciclo de vida de las larvas con mayor eficiencia productiva que los métodos convencionales.",
        imp1: "Eficiencia de Manejo: Reducimos significativamente el tiempo operativo en cada fase del ciclo productivo.",
        imp2: "Optimización de Recursos: Minimizamos el desperdicio de insumos orgánicos y maximizamos la productividad.",
        imp3: "Escalabilidad y Futuro: Ayudamos a los productores a expandir sus bio-fábricas con equipos modulares que satisfacen la demanda.",
        btnImpacto: "Vea nuestro impacto",
        praTit: "Del Impacto a la Práctica",
        praSub: "Nuestros productos se centran en la eficiencia reproductiva de los insectos, como las larvas.",
        btnCatalogo: "Catálogo de Productos",
        card1Tit: "Caja Reproductora",
        card1Desc: "La primera caja autoapilable de América Latina.",
        btnSaibaMais: "Saber Más",
        emBreve: "Próximamente...",
        intTit: "¿Interesado?",
        intSub: "Somos desarrolladores y entusiastas de la sostenibilidad enfocados en optimizar cada fase del ciclo de las larvas.",
        btnHistoria: "Nuestra historia",
        btnChegar: "Cómo llegar",
        intP1: "Smart Bugs nació del deseo de transformar el panorama de la biotecnología a través de soluciones inteligentes y accesibles. Combinamos tecnología y biología para ofrecer herramientas que realmente marcan la diferencia en la producción de proteínas sostenibles.",
        intP2: "Nuestro compromiso es con la innovación, la sostenibilidad y el éxito de nuestros clientes. Estamos aquí para ayudarle a lograr resultados extraordinarios, optimizando cada etapa del ciclo de producción de larvas con eficiencia y responsabilidad ambiental.",
        intP3: "Únase a nosotros en este viaje de transformación y descubra cómo Smart Bugs puede impulsar el futuro de la biotecnología, haciendo que el proceso de cría de insectos sea más inteligente, eficiente y sostenible.",
        footSub: "Tecnología que impulsa la biotecnología",
        footProd: "Productos",
        footMais: "Más Smart",
        footCont: "Contactos",
        btnEquipe: "Únete a nuestro equipo",
        footCaixa: "Caja de reproducción",
        footDescubra: "Descubre nuestra historia",
        footPlanejamos: "¿Adónde pensamos ir?"
    }
};