const traducoes = {
    pt: {
        // Globais (Header e Footer)
        "navInicio": "Início",
        "navLocalizacao": "Localização",
        "navImpacto": "Impacto",
        "navProdutos": "Produtos",
        "navSobreNos": "Sobre nós",
        "footSub": "Tecnologia que impulsiona a biotecnologia",
        "footProd": "Produtos",
        "footMais": "Mais Smart",
        "footCont": "Contatos",
        "btnEquipe": "Faça parte da nossa equipe",

        // Específicos da página Localização
        "locHeroBread": "Início > Localização",
        "locHeroTitle": "Descubra a nossa localização e melhore sua produtividade",
        "locInstalacaoTitulo": "Nossa instalação",
        "locComoChegarTitulo": "Como chegar",
        "locEndereco": "Rodovia estadual - conexão com BR - PR-182 - Biopark, Toledo - PR, 85906-300",
        "locMapaTexto": "Estamos localizados em Toledo - PR",
        "locMapaBtn": "Abrir no Google Maps",
        "locContatosTitulo": "Contatos",
        "locFaleConoscoTitulo": "Fale Conosco",
        "locFaleConoscoSub": "Escolha o canal mais conveniente para você. Nossa equipe de suporte está pronta para ajudar.",
        "locEmailLabel": "E-mail",
        "locAtendTitulo": "Área de Atendimento",
        "locAtendCard1Tit": "Horário de Funcionamento",
        "locAtendCard1Desc": "Atendemos de Segunda a Sexta-feira, das 08h às 17h.",
        "locAtendCard2Tit": "Logística e Envios",
        "locAtendCard2Desc": "Contratamos transportadoras para grandes unidades ou Correios para pedidos menores. Você também pode retirar diretamente conosco.",
        "locAtendCard3Tit": "Faça seu Pedido",
        "locAtendCard3Desc": "Venha fazer seu pedido e conferir nosso Instagram.",
        "locAtendCard3Btn": "Acessar Link.tree",
        "locAtendCard4Tit": "Ficou com Dúvidas?",
        "locAtendCard4Desc": "Nossa equipe está à disposição para te ajudar rapidamente.",
        "locAtendCard4Btn": "Chamar no WhatsApp",
        "locTrabalhoTitulo": "Nosso trabalho"
    },
    en: {
        // Globais
        "navInicio": "Home",
        "navLocalizacao": "Location",
        "navImpacto": "Impact",
        "navProdutos": "Products",
        "navSobreNos": "About us",
        "footSub": "Technology driving biotechnology",
        "footProd": "Products",
        "footMais": "More Smart",
        "footCont": "Contacts",
        "btnEquipe": "Join our team",

        // Específicos da página Localização
        "locHeroBread": "Home > Location",
        "locHeroTitle": "Discover our location and boost your productivity",
        "locInstalacaoTitulo": "Our Facility",
        "locComoChegarTitulo": "How to get here",
        "locEndereco": "State Highway - BR connection - PR-182 - Biopark, Toledo - PR, Brazil, 85906-300",
        "locMapaTexto": "We are located in Toledo - PR, Brazil",
        "locMapaBtn": "Open in Google Maps",
        "locContatosTitulo": "Contacts",
        "locFaleConoscoTitulo": "Get in Touch",
        "locFaleConoscoSub": "Choose the most convenient channel for you. Our support team is ready to help.",
        "locEmailLabel": "E-mail",
        "locAtendTitulo": "Service Area",
        "locAtendCard1Tit": "Business Hours",
        "locAtendCard1Desc": "We are open Monday through Friday, from 8 AM to 5 PM.",
        "locAtendCard2Tit": "Logistics & Shipping",
        "locAtendCard2Desc": "We use carriers for larger units or postal services for smaller orders. You can also pick up directly from us.",
        "locAtendCard3Tit": "Place Your Order",
        "locAtendCard3Desc": "Come place your order and check out our Instagram.",
        "locAtendCard3Btn": "Access Linktr.ee",
        "locAtendCard4Tit": "Have Questions?",
        "locAtendCard4Desc": "Our team is available to assist you quickly.",
        "locAtendCard4Btn": "Chat on WhatsApp",
        "locTrabalhoTitulo": "Our Work"
    },
    es: {
        // Globais
        "navInicio": "Inicio",
        "navLocalizacao": "Ubicación",
        "navImpacto": "Impacto",
        "navProdutos": "Productos",
        "navSobreNos": "Sobre nosotros",
        "footSub": "Tecnología que impulsa la biotecnología",
        "footProd": "Productos",
        "footMais": "Más Smart",
        "footCont": "Contactos",
        "btnEquipe": "Forma parte de nuestro equipo",

        // Específicos da página Localização
        "locHeroBread": "Inicio > Ubicación",
        "locHeroTitle": "Descubre nuestra ubicación y mejora tu productividad",
        "locInstalacaoTitulo": "Nuestra Instalación",
        "locComoChegarTitulo": "Cómo llegar",
        "locEndereco": "Carretera estatal - conexión con BR - PR-182 - Biopark, Toledo - PR, Brasil, 85906-300",
        "locMapaTexto": "Estamos ubicados en Toledo - PR, Brasil",
        "locMapaBtn": "Abrir en Google Maps",
        "locContatosTitulo": "Contactos",
        "locFaleConoscoTitulo": "Hable con Nosotros",
        "locFaleConoscoSub": "Elija el canal más conveniente para usted. Nuestro equipo de soporte está listo para ayudar.",
        "locEmailLabel": "Correo",
        "locAtendTitulo": "Área de Atención",
        "locAtendCard1Tit": "Horario de Atención",
        "locAtendCard1Desc": "Atendemos de Lunes a Viernes, de 08h a 17h.",
        "locAtendCard2Tit": "Logística y Envíos",
        "locAtendCard2Desc": "Contratamos transportistas para unidades grandes o Correos para pedidos menores. También puedes retirar directamente con nosotros.",
        "locAtendCard3Tit": "Haz tu Pedido",
        "locAtendCard3Desc": "Ven a hacer tu pedido y revisa nuestro Instagram.",
        "locAtendCard3Btn": "Acceder a Linktr.ee",
        "locAtendCard4Tit": "¿Tienes Dudas?",
        "locAtendCard4Desc": "Nuestro equipo está a disposición para ayudarte rápidamente.",
        "locAtendCard4Btn": "Contactar por WhatsApp",
        "locTrabalhoTitulo": "Nuestro Trabajo"
    }
};