const traducoes = {
    pt: {
        navInicio: "Início",
        navLocalizacao: "Localização",
        navImpacto: "Impacto",
        navProdutos: "Produtos",
        navSobreNos: "Sobre nós",
        heroTitulo: "Inicio > Sobre Nós",
        heroDescricao: "Potencializar a criação de larvas",
        conteudoTitulo: "Inovação que gera eficiência",
        conteudoParagrafo1: "Somos os criadores da primeira e única Caixa para Reprodução de Larvas patenteada no Brasil. Mais do que acompanhar o mercado, nós lideramos a inovação bioindustrial no país.",
        conteudoParagrafo2: "Desenvolvida com tecnologia própria e foco total em biossegurança, nossa solução é 100% livre de bisfenol (BPA), garantindo a pureza absoluta da cadeia alimentar desde a base.",
        tagDiretrizes: "Diretrizes",
        pilaresTitulo: "Pilares que sustentam nossa inovação",
        pilar1Titulo: "Inovação Biotecnológica",
        pilar1Descricao: "Transformamos ciência em soluções práticas. Desenvolvemos ferramentas inteligentes baseadas em biotecnologia de ponta para simplificar o manejo e redefinir o cultivo.",
        pilar2Titulo: "Estratégia e Escalabilidade",
        pilar2Descricao: "Planejado para crescer com você. Criamos sistemas flexíveis e modulares que eliminam gargalos operacionais, garantindo rápido retorno sobre o investimento.",
        pilar3Titulo: "Sustentabilidade Circular",
        pilar3Descricao: "Alta performance com desperdício zero. Tecnologia focada no reaproveitamento inteligente de recursos biológicos para construir um ecossistema produtivo limpo.",
        pilar4Titulo: "Eficiência Operacional",
        pilar4Descricao: "Simplificação de processos complexos. Reduzimos o tempo de manejo através de designs funcionais, permitindo atingir a máxima performance com menor esforço.",
        avalTitulo1: "Avaliações",
        avalTitulo2: "dos Produtos",
        depoimentoMaria: "Excelente ergonomia e controle de umidade. A taxa de eclosão e reprodução aumentou drasticamente aqui!",
        depoimentoJulia: "Material super resistente e fácil de higienizar. O design da caixa otimizou 100% o manejo diário.",
        depoimentoRoman: "Inovação pura na biotecnologia. Caixa compacta, sem cheiro e ideal para manter o ciclo sustentável.",
        tagProcesso: "Processo",
        cicloTitulo: "Ciclo de Produção Sustentável",
        ciclo1Titulo: "Resíduo Orgânico",
        ciclo1Descricao: "A entrada do desperdício de alimentos. Frutas, vegetais e restos orgânicos.",
        badgePatenteado: "Patenteado",
        ciclo2Titulo: "Manejo Eficiente",
        ciclo2Descricao: "As larvas (BSF) se alimentam dentro das caixas autoempilháveis patenteadas.",
        ciclo3Titulo: "Processamento",
        ciclo3Descricao: "Transformação das larvas em proteína e óleos nobres.",
        ciclo4Titulo: "Nutrição Sustentável",
        ciclo4Descricao: "O produto final chega ao mercado de rações e pet food."
    },
    en: {
        "navInicio": "Home",
        "navLocalizacao": "Location",
        "navImpacto": "Impact",
        "navProdutos": "Products",
        "navSobreNos": "About us",
        "footSub": "Technology driving biotechnology",
        "footProd": "Products",
        "footMais": "More Smart",
        "footCont": "Contacts",
        "btnEquipe": "Join our team",
        "footLinkHist": "Discover our story",
        "footLinkPlan": "Where we plan to go",
        
        heroTitulo: "Home > About Us",
        heroDescricao: "Empowering larvae breeding",
        conteudoTitulo: "Innovation that drives efficiency",
        conteudoParagrafo1: "We are the creators of the first and only Larvae Breeding Box patented in Brazil. More than keeping up with the market, we lead bioindustrial innovation in the country.",
        conteudoParagrafo2: "Developed with our own technology and total focus on biosecurity, our solution is 100% free of bisphenol (BPA), ensuring absolute purity of the food chain from the ground up.",
        tagDiretrizes: "Guidelines",
        pilaresTitulo: "Pillars that sustain our innovation",
        pilar1Titulo: "Biotechnological Innovation",
        pilar1Descricao: "We turn science into practical solutions. We develop smart tools based on cutting-edge biotechnology to simplify handling and redefine farming.",
        pilar2Titulo: "Strategy and Scalability",
        pilar2Descricao: "Planned to grow with you. We create flexible and modular systems that eliminate operational bottlenecks, ensuring quick return on investment.",
        pilar3Titulo: "Circular Sustainability",
        pilar3Descricao: "High performance with zero waste. Technology focused on the smart reuse of biological resources to build a clean productive ecosystem.",
        pilar4Titulo: "Operational Efficiency",
        pilar4Descricao: "Simplification of complex processes. We reduce handling time through functional designs, allowing you to achieve maximum performance with less effort.",
        avalTitulo1: "Product",
        avalTitulo2: "Reviews",
        depoimentoMaria: "Excellent ergonomics and humidity control. The hatching and reproduction rate has increased drastically here!",
        depoimentoJulia: "Super resistant material and easy to clean. The box design optimized daily management 100%.",
        depoimentoRoman: "Pure innovation in biotechnology. Compact box, odorless, and ideal for maintaining a sustainable cycle.",
        tagProcesso: "Process",
        cicloTitulo: "Sustainable Production Cycle",
        ciclo1Titulo: "Organic Waste",
        ciclo1Descricao: "The intake of food waste. Fruits, vegetables, and organic scraps.",
        badgePatenteado: "Patented",
        ciclo2Titulo: "Efficient Management",
        ciclo2Descricao: "Larvae (BSF) feed inside the patented self-stacking boxes.",
        ciclo3Titulo: "Processing",
        ciclo3Descricao: "Transformation of larvae into high-quality protein and noble oils.",
        ciclo4Titulo: "Sustainable Nutrition",
        ciclo4Descricao: "The final product reaches the feed and pet food market.",
        footCaixa: "Reproduction Box",
        footDescubra: "Discover our history",
        footPlanejamos: "Where do we plan to go"
    },
    es: {
        "navInicio": "Inicio",
        "navLocalizacao": "Ubicación",
        "navImpacto": "Impacto",
        "navProdutos": "Productos",
        "navSobreNos": "Sobre nosotros",
        "footSub": "Tecnología que impulsa la biotecnología",
        "footProd": "Productos",
        "footMais": "Más Smart",
        "footCont": "Contactos",
        "btnEquipe": "Forma parte de nuestro equipo",
        "footLinkHist": "Descubre nuestra historia",
        "footLinkPlan": "A dónde planeamos llegar",
        "emBreve": "Próximamente...",
        heroTitulo: "Inicio > Sobre Nosotros",
        heroDescricao: "Potenciar la cría de larvas",
        conteudoTitulo: "Innovación que genera eficiencia",
        conteudoParagrafo1: "Somos los creadores de la primera y única Caja para Reproducción de Larvas patentada en Brasil. Más que seguir el mercado, lideramos la innovación bioindustrial en el país.",
        conteudoParagrafo2: "Desarrollada con tecnología propia y enfoque total en bioseguridad, nuestra solución es 100% libre de bisfenol (BPA), garantizando la pureza absoluta de la cadena alimentaria desde la base.",
        tagDiretrizes: "Directrices",
        pilaresTitulo: "Pilares que sustentan nuestra innovación",
        pilar1Titulo: "Innovación Biotecnológica",
        pilar1Descricao: "Transformamos la ciencia en soluciones prácticas. Desarrollamos herramientas inteligentes basadas en biotecnología de punta para simplificar el manejo y redefinir el cultivo.",
        pilar2Titulo: "Estrategia y Escalabilidad",
        pilar2Descricao: "Planificado para crecer contigo. Creamos sistemas flexibles y modulares que eliminan los cuellos de botella operativos, garantizando un rápido retorno de la inversión.",
        pilar3Titulo: "Sustentabilidad Circular",
        pilar3Descricao: "Alto rendimiento con cero desperdicios. Tecnología enfocada en el reaprovechamiento inteligente de recursos biológicos para construir un ecosistema productivo limpio.",
        pilar4Titulo: "Eficiencia Operativa",
        pilar4Descricao: "Simplificación de procesos complejos. Reducimos el tempo de manejo a través de diseños funcionales, permitiendo alcanzar el máximo rendimiento con menor esfuerzo.",
        avalTitulo1: "Evaluaciones",
        avalTitulo2: "de los Productos",
        depoimentoMaria: "¡Excelente ergonomía y control de humedad. La tasa de eclosión y reproducción aumentó drásticamente aquí!",
        depoimentoJulia: "Material súper resistente y fácil de limpiar. El diseño de la caja optimizó el manejo diario al 100%.",
        depoimentoRoman: "Pura innovación en biotecnología. Caja compacta, sin olor e ideal para mantener el ciclo sostenible.",
        tagProcesso: "Proceso",
        cicloTitulo: "Ciclo de Producción Sostenible",
        ciclo1Titulo: "Residuos Orgánicos",
        ciclo1Descricao: "La entrada del desperdicio de alimentos. Frutas, verduras y restos orgánicos.",
        badgePatenteado: "Patentado",
        ciclo2Titulo: "Manejo Eficiente",
        ciclo2Descricao: "Las larvas (BSF) se alimentan dentro de las cajas autoapilables patentadas.",
        ciclo3Titulo: "Procesamiento",
        ciclo3Descricao: "Transformación de las larvas en proteínas y aceites nobles.",
        ciclo4Titulo: "Nutrición Sostenible",
        ciclo4Descricao: "El producto final llega al mercado de alimentos para animales y pet food.",
        footCaixa: "Reproduction Box",
        footDescubra: "Discover our history",
        footPlanejamos: "Where do we plan to go"
    }
};